import json
import os
import urllib.request

# CONFIG
MERAKI_URL = "https://cdn.merakianalytics.com/riot/lol/resources/latest/en-US/champions.json"
STATS_PATH = "/opt/clawdbot/projects/LOL-game-analyzer/backend/champion_stats_pro.json" # NEW STATS FILE
OUTPUT_TS_PATH = "/opt/clawdbot/projects/LOL-game-analyzer/data/championTags.ts"

def clean_role(role):
    r = role.lower()
    if r == "middle": return "mid"
    if r == "bottom": return "bot"
    if r == "utility": return "support"
    return r

def generate_frontend_data():
    print("🔄 Merging Data (Meraki Static + Pro Stats + Global Rates)...")
    
    # 1. Fetch Meraki Static Data (Roles/Classes)
    try:
        with urllib.request.urlopen(MERAKI_URL) as url:
            meraki_data = json.loads(url.read().decode())
    except Exception as e:
        print(f"   ❌ Failed to download Meraki data: {e}")
        return

    # 2. Load Stats (Pro Winrates + Global Pickrates)
    try:
        with open(STATS_PATH, 'r') as f:
            stats_data = json.load(f)
    except:
        print("   ⚠️ Stats file not found, using defaults.")
        stats_data = {}

    final_data = {}
    
    for key, data in meraki_data.items():
        real_name = data['name']
        official_roles = [r.title() for r in data.get('roles', [])] 
        
        raw_attack = data.get('attackType', 'Unknown')
        attack_type = raw_attack.title() if raw_attack else "Unknown"

        raw_positions = data.get('positions', [])
        clean_positions = set()
        for p in raw_positions:
            clean_positions.add(clean_role(p))
            
        if real_name == "Anivia" and "top" in clean_positions: clean_positions.remove("top")
        if real_name == "Cassiopeia" and "top" in clean_positions: clean_positions.remove("top")
            
        if not clean_positions: clean_positions.add("mid") 

        # Get Stats
        s = stats_data.get(real_name, {})
        
        final_data[real_name] = {
            "id": data['key'],
            "name": real_name,
            "title": data['title'],
            "classes": official_roles,
            "roles": list(clean_positions),
            "attackType": attack_type,
            "stats": {
                "proWinRate": s.get('pro_win_rate', 0),
                "proPickRate": s.get('pro_pick_rate', 0),
                "globalPickRate": s.get('global_pick_rate', 0),
                "globalWinRate": s.get('global_win_rate', None) # Placeholder
            }
        }

    # Write TS
    ts_content = f"// Auto-generated by update_frontend_data.py\n"
    ts_content += f"export const CHAMPION_DATA: Record<string, {{ id: string, name: string, title: string, classes: string[], roles: string[], attackType: string, stats: {{ proWinRate: number, proPickRate: number, globalPickRate: number, globalWinRate: number | null }} }}> = "
    ts_content += json.dumps(final_data, indent=2)
    ts_content += ";\n"
    
    os.makedirs(os.path.dirname(OUTPUT_TS_PATH), exist_ok=True)
    with open(OUTPUT_TS_PATH, 'w') as f:
        f.write(ts_content)
        
    print(f"✅ Generated {OUTPUT_TS_PATH} with {len(final_data)} champions.")

if __name__ == "__main__":
    generate_frontend_data()
